# Dishita Mohan
# Registration no: 210968054
# Week 8

# 1.Summary of MovieLens Metadata:

This dataset was generated on September 26, 2018.
Format: CSV with single header row. Encoding: UTF-8

1.Contains 100836 ratings and 3683 tag applications across 9742 movies

2.Users selected at random for inclusion. All selected users had rated at least 20 movies

3.Ratings are made on a 5-star scale, with half-star increments (0.5 stars - 5.0 stars).

4.Timestamps represent seconds since midnight Coordinated Universal Time (UTC) of January 1, 1970.

5.Movie titles are entered manually or imported from https://www.themoviedb.org/, and include the year of release in parentheses. Errors and inconsistencies may exist in these titles.

6.Genres are a pipe-separated list, and are selected from the following:
Action Adventure Animation Children's Comedy Crime Documentary Drama Fantasy Film-Noir Horror Musical Mystery Romance Sci-Fi Thriller War Western (no genres listed)


In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
import datetime

from sklearn.metrics import pairwise_distances as pair
from scipy.spatial.distance import cosine, correlation


df1 = pd.read_csv('links.csv')
df2 = pd.read_csv('movies.csv')
df3 = pd.read_csv('ratings.csv')
df4 = pd.read_csv('tags.csv')

In [59]:
df=df1.merge(df2, left_on='movieId', right_on='movieId', how='left')
df=df.merge(df3, left_on='movieId', right_on='movieId', how='left')
df=df.merge(df4, left_on='movieId', right_on='movieId', how='left')
df

movieId   imdbId    tmdbId                                      title  \
0             1   114709     862.0                           Toy Story (1995)   
1             1   114709     862.0                           Toy Story (1995)   
2             1   114709     862.0                           Toy Story (1995)   
3             1   114709     862.0                           Toy Story (1995)   
4             1   114709     862.0                           Toy Story (1995)   
...         ...      ...       ...                                        ...   
285778   193581  5476944  432131.0  Black Butler: Book of the Atlantic (2017)   
285779   193583  5914996  445030.0               No Game No Life: Zero (2017)   
285780   193585  6397426  479308.0                               Flint (2017)   
285781   193587  8391976  483455.0        Bungo Stray Dogs: Dead Apple (2018)   
285782   193609   101726   37891.0        Andrew Dice Clay: Dice Rules (1991)   

                                             genres  userId_x  rating  \
0       Adventure|Animation|Children|Comedy|Fantasy       1.0     4.0   
1       Adventure|Animation|Children|Comedy|Fantasy       1.0     4.0   
2       Adventure|Animation|Children|Comedy|Fantasy       1.0     4.0   
3       Adventure|Animation|Children|Comedy|Fantasy       5.0     4.0   
4       Adventure|Animation|Children|Comedy|Fantasy       5.0     4.0   
...                                             ...       ...     ...   
285778              Action|Animation|Comedy|Fantasy     184.0     4.0   
285779                     Animation|Comedy|Fantasy     184.0     3.5   
285780                                        Drama     184.0     3.5   
285781                             Action|Animation     184.0     3.5   
285782                                       Comedy     331.0     4.0   

         timestamp_x  userId_y    tag   timestamp_y  
0       9.649827e+08     336.0  pixar  1.139046e+09  
1       9.649827e+08     474.0  pixar  1.137207e+09  
2       9.649827e+08     567.0    fun  1.525286e+09  
3       8.474350e+08     336.0  pixar  1.139046e+09  
4       8.474350e+08     474.0  pixar  1.137207e+09  
...              ...       ...    ...           ...  
285778  1.537109e+09       NaN    NaN           NaN  
285779  1.537110e+09       NaN    NaN           NaN  
285780  1.537110e+09       NaN    NaN           NaN  
285781  1.537110e+09       NaN    NaN           NaN  
285782  1.537158e+09       NaN    NaN           NaN  

[285783 rows x 11 columns]

In [60]:
#2. Read the “ratings.csv” file and create a pivot table with index=‘userId’, columns=‘movieId’, values = “rating".

dff = df3.pivot_table(index='userId', columns='movieId', values='rating',fill_value=0, aggfunc=np.mean)

dff

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0       0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     0.0     0.0     0.0     0.0     0.0     2.5       0   
607         4.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
608         2.5     2.0     2.0     0.0     0.0     0.0     0.0       0   
609         3.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
610         5.0     0.0     0.0     0.0     0.0     5.0     0.0       0   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0       0       0       0     0.0       0   
2           0.0     0.0  ...     0.0       0       0       0     0.0       0   
3           0.0     0.0  ...     0.0       0       0       0     0.0       0   
4           0.0     0.0  ...     0.0       0       0       0     0.0       0   
5           0.0     0.0  ...     0.0       0       0       0     0.0       0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         0.0     0.0  ...     0.0       0       0       0     0.0       0   
607         0.0     0.0  ...     0.0       0       0       0     0.0       0   
608         0.0     4.0  ...     0.0       0       0       0     0.0       0   
609         0.0     4.0  ...     0.0       0       0       0     0.0       0   
610         0.0     0.0  ...     0.0       0       0       0     0.0       0   

movieId  193583  193585  193587  193609  
userId                                   
1           0.0     0.0     0.0       0  
2           0.0     0.0     0.0       0  
3           0.0     0.0     0.0       0  
4           0.0     0.0     0.0       0  
5           0.0     0.0     0.0       0  
...         ...     ...     ...     ...  
606         0.0     0.0     0.0       0  
607         0.0     0.0     0.0       0  
608         0.0     0.0     0.0       0  
609         0.0     0.0     0.0       0  
610         0.0     0.0     0.0       0  

[610 rows x 9724 columns]

In [61]:
#3. sklearn.metrics.pairwise_distances can be used to compute distance between all pairs of 
#users. pairwise_distances() takes a metric parameter for what distance measure to use. 
#Use cosine similarity for finding similarity among users. Use the following packages

pair=pairwise_distances(dff, Y=None, metric='cosine')
pair


array([[0.00000000e+00, 9.72717135e-01, 9.40279738e-01, ...,
        7.08902628e-01, 9.06428070e-01, 8.54679193e-01],
       [9.72717135e-01, 1.11022302e-16, 1.00000000e+00, ...,
        9.53789046e-01, 9.72434599e-01, 8.97573246e-01],
       [9.40279738e-01, 1.00000000e+00, 0.00000000e+00, ...,
        9.78871538e-01, 1.00000000e+00, 9.67881252e-01],
       ...,
       [7.08902628e-01, 9.53789046e-01, 9.78871538e-01, ...,
        0.00000000e+00, 8.78007286e-01, 6.77945142e-01],
       [9.06428070e-01, 9.72434599e-01, 1.00000000e+00, ...,
        8.78007286e-01, 0.00000000e+00, 9.46774537e-01],
       [8.54679193e-01, 8.97573246e-01, 9.67881252e-01, ...,
        6.77945142e-01, 9.46774537e-01, 1.11022302e-16]])

In [62]:
#6. Find the 5 most similar user for user with user Id 25.

print((-pair[24]).argsort()[1:6]+1)

[161 163 546 170 175]


In [63]:
#7. Use the “movies” dataset to find out the names of movies, user 1 and user 338 have watched in common and how they have rated each one of them.

common_movies = set(df3.loc[df3.userId==1, 'movieId']).intersection(set(df3.loc[df3.userId==338, 'movieId']))
common_movies

{50, 296, 527, 593, 2959}

In [69]:
#8. Use the movies dataset to find out the common movie names between user 2 and user 338 with least rating of 4.0


# common_movies2 = set(df3.loc[df3.userId==2, 'movieId']).intersection(set(df3.loc[df3.userId==338, 'movieId']))
common_movies2 = set(df3.loc[((df3.userId==2) & (df3.rating>=4.0)), 'movieId']).intersection(set(df3.loc[((df3.userId==338) & (df3.rating>=4.0)), 'movieId']))

common_movies2


for movieid in sorted(common_movies2):
    common = df2[df2['movieId'] == movieid]
    print(common)

      movieId                     title                 genres
4615     6874  Kill Bill: Vol. 1 (2003)  Action|Crime|Thriller


In [68]:
#9. Create a pivot table for representing the similarity among movies using correlation.

dff = pd.pivot_table(df3, index='movieId', columns='userId', values='rating', fill_value=0)

pair2=pairwise_distances(dff, Y=None, metric='correlation')

pair2


array([[0.        , 0.7686735 , 0.8267872 , ..., 1.0289057 , 1.0289057 ,
        1.0289057 ],
       [0.7686735 , 0.        , 0.80805513, ..., 1.01829073, 1.01829073,
        1.01829073],
       [0.8267872 , 0.80805513, 0.        , ..., 1.01172923, 1.01172923,
        1.01172923],
       ...,
       [1.0289057 , 1.01829073, 1.01172923, ..., 0.        , 0.        ,
        1.00164204],
       [1.0289057 , 1.01829073, 1.01172923, ..., 0.        , 0.        ,
        1.00164204],
       [1.0289057 , 1.01829073, 1.01172923, ..., 1.00164204, 1.00164204,
        0.        ]])

In [71]:
#10.Find the top 5 movies which are similar to the movie “Godfather”.

for movie in df2.title:
    if('Godfather' in str(movie)):
        print(movie)

Godfather, The (1972)
Godfather: Part II, The (1974)
Godfather: Part III, The (1990)
Tokyo Godfathers (2003)
The Godfather Trilogy: 1972-1990 (1992)


In [72]:
df2.loc[(df2.title=='Godfather, The (1972)'), 'movieId'].values[0]


858

In [74]:
similar_movies = pair2[857].argsort()[1:6]+1
similar_movies

array([2763, 2757, 1475, 2247, 1803], dtype=int64)

In [76]:
for movieID in similar_movies:
    print(df2[df2["movieId"] == movieID])
    print("\n")

      movieId                            title          genres
2079     2763  Thomas Crown Affair, The (1999)  Action|Mystery


      movieId           title genres
2075     2757  Frances (1982)  Drama


      movieId                              title   genres
1128     1475  Kama Sutra: A Tale of Love (1996)  Romance


      movieId                      title  genres
1670     2247  Married to the Mob (1988)  Comedy


Empty DataFrame
Columns: [movieId, title, genres]
Index: []


